spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rus
    username: root
    password: Admin123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always