spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rusdb
    username: admin
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: always
  liquibase:
    enabled: true
    change-log: classpath:liquibase/db.changelog-master.xml
logging:
  level:
    liquibase: debug

hibernate:
  cache:
    use_second_level_cache: true
    region:
      factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory