spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rus
    username: root
    password: Admin123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
  liquibase:
    enabled: true
    change-log: classpath:liquibase/db.changelog-master.xml